# Generated by Django 4.2.13 on 2024-06-03 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosaTrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
