# Generated by Django 4.2.13 on 2024-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosaTrip', '0002_trip_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='description',
        ),
    ]
