# Generated by Django 5.1a1 on 2024-06-06 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RosaTrip', '0003_veiculo_remove_trip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
    ]
