# Generated by Django 5.0.6 on 2024-06-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RosaTrip', '0005_cadastropendente_delete_trip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadastroPendente',
        ),
    ]
