# Generated by Django 5.1b1 on 2024-08-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosaTrip', '0006_delete_cadastropendente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='RosaTrip/'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marca_veiculo', to='RosaTrip.marca'),
        ),
    ]
