# Generated by Django 5.1b1 on 2024-08-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RosaTrip', '0007_marca_alter_veiculo_foto_alter_veiculo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='ano',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano_fabricacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano_modelo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
